exclude: |
  (?x)^(
    .*.interp |
    .*.tokens |
    Sources\/Schema\/.*.swift |
    Sources\/Template\/.*.swift
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: swiftformat
        name: SwiftFormat
        entry: "mint run swiftformat"
        language: system
        types: [swift]
      - id: swiftlint
        name: SwiftLint
        entry: "mint run swiftlint --quiet"
        language: system
        types: [swift]
